config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: "users/sessions", omniauth_callbacks: 'omniauth_callbacks' }

  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup

  root 'decisions#new'

  # devise_scope :user do
  #  get "signup", to: "devise/registrations#new"
  #  get "login", to: "devise/sessions#new"
  #  get "logout", to: "devise/sessions#destroy"
  # end

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  resources :decisions, :users, :arbiters, :votes, :preferences

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/decision.rb
class Decision < ActiveRecord::Base
	belongs_to :arbiter
	belongs_to :type
	has_one :firstoption
	has_one :secondoption
	has_many :votes, through: :firstoption
	has_many :votes, through: :secondoption


	def display_app_choice
		if self.app_choice == 0
			return self.firstoption.description
		elsif self.app_choice ==1 
			return self.secondoption.description
		else
			return "No choice made"
		end
	end
	def display_user_choice
		if self.user_choice == 0
			return self.firstoption.description
		elsif self.user_choice ==1 
			return self.secondoption.description
		else
			return "No choice made"
		end
	end
	
	def user_choice_assign(commit)
		if commit == "I took your advice"
			self.user_choice = self.app_choice
		elsif commit == "I'm going with the other one"
			if self.app_choice == 0
				self.user_choice = 1
			elsif self.app_choice == 1
				self.user_choice = 0
			else
				flash[:notice] = "bad commit"
			end
		end			
	end	

	def log_results_in_preference
		# update preference
	    @preference = self.arbiter.preferences.where(type: self.type).last
	    @preference.modify_preference(self.user_choice)
	end
	def name
		self.firstoption.description + " or " + self.secondoption.description
	end
	def find_preference
		self.arbiter.preferences.where(type: self.type).last
	end

	def voting_percent(option)
		if self.total_votes() == 0
			return 50
		end
		if option == 0
			100*self.firstoption.votes.count()/(self.firstoption.votes.count() + self.secondoption.votes.count())
		elsif option ==1
			100*self.secondoption.votes.count()/(self.firstoption.votes.count() + self.secondoption.votes.count())
		else
			return "BAD SELECT"
		end
		
	end
	def total_votes
		self.firstoption.votes.count() + self.secondoption.votes.count()
	end
end

app/controllers/decisions_controller.rb
class DecisionsController < ApplicationController
  def index
    @user_decisions=Decision.where.not(description: "").where(arbiter_id: current_user.arbiter.id)
    @other_decisions=Decision.where.not(arbiter_id: current_user.arbiter.id).where(voting_open: true)
  end

  def new
    if user_signed_in? && current_user.arbiter == nil
      @arbiter=Arbiter.create()
      current_user.arbiter=@arbiter
      @arbiter.save
    end
    @decision=Decision.new
    @firstoption=Firstoption.new
    @secondoption=Secondoption.new
  end

  def create
    @decision=Decision.new(decision_params)
    if user_signed_in?
      current_user.arbiter.decisions << @decision
      @preference = @decision.find_preference()
      # Create Preference if one does not exist
      unless @preference
        puts "=========MAKING PREFERENCE=============="
        @preference=Preference.create(a_score: 1, b_score: 1)
        @decision.arbiter.preferences << @preference
        @decision.type.preferences << @preference
      end
      # make app_choice by calling function on preference
      @decision.app_choice = @preference.make_choice
    else
      # make this take global preferences into account?
      @decision.app_choice = rand(2)
    end
    @decision.description == "" ? @decision.voting_open = false : @decision.voting_open = true
    if @decision.save
      # create first option and give it name from type if user does not specify
      @firstoption=Firstoption.create(description: params[:decision][:firstoption][:description])
      @firstoption.description = @decision.type.possibility_name(0) if @firstoption.description == ""
      # create second option and give it name from type if user does not specify
      @secondoption=Secondoption.create(description: params[:decision][:secondoption][:description])
      @secondoption.description = @decision.type.possibility_name(1) if @secondoption.description == ""
      # attach options to decision
      @decision.firstoption=@firstoption
      @decision.secondoption=@secondoption
      redirect_to edit_decision_path(@decision)
    else
      flash[:notice] = "Invalid Decision"
      redirect_to root_path
    end
  end

  def show
    @vote=Vote.new
    @decision=Decision.find(params[:id])
  end

  def edit
    @decision=Decision.find(params[:id])
  end

  def update
    @decision=Decision.find(params[:id])
    if params[:commit] == "Turn Off Voting"
      @decision.voting_open=false
    elsif params[:commit] == "Turn On Voting"
      @decision.voting_open=true
    else
      @decision.user_choice_assign(params[:commit])
    end    
    if @decision.save
      @decision.log_results_in_preference() if user_signed_in?
      redirect_to decision_path(@decision)
    else
      flash[:notice] = "Could not update Decision"
      redirect_to new_decision_path
    end
  end
  
  def destroy
    Decision.find(params[:id]).destroy
    redirect_to decisions_path
  end

  private

  def decision_params
    params.require(:decision).permit(:type_id, :description)   
  end
end

app/helpers/decisions_helper.rb
module DecisionsHelper
end

app/views/decisions/create.html.erb
<h1>Decisions#create</h1>
<p>Find me in app/views/decisions/create.html.erb</p>

app/views/decisions/destroy.html.erb
<h1>Decisions#destroy</h1>
<p>Find me in app/views/decisions/destroy.html.erb</p>

app/views/decisions/edit.html.erb
<div class="prompt_page">
	<div class="result advice">
		<%= content_tag :h2, "We think you should do:" %>
		<%= content_tag :h4, @decision.display_app_choice() %>
		<br><br><br>
	</div>
	<div class="result response">
		<%= content_tag :h2, "You have chosen:" %>
		<%= content_tag :h4, @decision.display_user_choice() %>
		<br><br><br>
	</div>
	<div class="prompt">
		<%= form_for @decision, url: decision_path(@decision), method: :put do |d| %>
		<br><br><br>
		<%= d.submit("I took your advice") %>
		<br><br><br>
		<br><br><br>
		<%= d.submit("I'm going with the other one") %>
		<% end %>
	</div>
</div>

app/views/decisions/index.html.erb
<div class="vote_board">
	<%= content_tag :h1, "Your Custom Decisions:" %>
	<div class="user_decisions">
		<% @user_decisions.each do |d| %>
			<div class="user_decision"><br><%=link_to d.name(), decision_path(d) %></div>
		<% end %>
		<% if @user_decisions.count() == 0 %>
			<h3>You have no custom decisions yet! Go make some!</h3>
		<% end %>
	</div>
</div>
<div class="vote_board">
	<%= content_tag :h1, "Decisions to vote on:" %>
	<% @other_decisions.each do |d| %>
	<table>
		<tr>
			<th>Votes for first option</th>
			<th>Decision name</th>
			<th>Votes for second option</th>
		</tr>
		
		<tr>
			<td class="other_a"><%= d.firstoption.votes.count() %></td> 
			<td class="other_name"><%= link_to d.name(), decision_path(d) %></td> 
			<td class="other_b"><%= d.secondoption.votes.count() %></td> 
		</tr>
		<% end %>
	</table>
	
	<h3>choose.</h3>
</div>

app/views/decisions/new.html.erb
<%= form_for @decision do |d| %>
	<%= content_tag :h3, "Pick a Decision Type:" %>
	<%= d.select(:type_id, Type.all.collect {|t| [ t.description, t.id ] }) %>
	<!-- make a hiding method for custom -->
	<div id="custom_dec_hider">
		<%= content_tag :h3, "Describe the decision you are facing:" %>
		<%= d.text_area :description, :id => "description", :placeholder => "Enter a description here and enable other users to vote on this decision" %>
		<div class="option_input" id="first_option_input">
			<%= d.fields_for @firstoption do |a| %>
			<%= content_tag :h3, "The first option is:", :id => "first_option_description" %>
			<%= a.text_field :description %>
			<% end %>
		</div>
		<div class="option_input" id="second_option_input">
			<%= d.fields_for @secondoption do |b| %>
			<%= content_tag :h3, "The second option is:", :id => "second_option_description" %>
			<%= b.text_field :description %>
			<% end %>
		</div>
	</div>
	<%= content_tag :h3, "Then hit:" %>
	<%= d.submit "choose." %>
	<% end %>
<% if user_signed_in? %>
	<br>
	<button id="hide_button">Custom Decision</button>
	<br>  
	<br>
	<article>
	<p>
		 The responses you give to the app's choices will be used to learn how to better advise you on future decisions of the same type. Go to your Profile to view your preferences across all of <strong>choose</strong>'s decision types. You can also click "Custom Decision" if you would like to ask the <strong>choose</strong> community to anonymously vote on your decision. 
		<br><br>
		 Thank you for signing up for <strong>choose</strong>, if you would like to know more about the application you can check it out on <strong><a href="https://github.com/MichaelManwaring/ux_decide">Github<a/></strong>.
	</p>
</article>
<% else %>
<br>
<br>
<article>
	<p>
		Life in the 21<sup>st</sup> Century is overloaded with choice, and taking the time to ponder every decision will leave you hung up on the details. <strong>choose</strong> is here to make that easier by helping you decide between two options. Select a category above and start making decisions or sign up and allow <strong>choose</strong> to start learning your preferences, as well as creating and voting on custom decisions. 
		<br><br>
		Check out the <strong><a href="https://github.com/MichaelManwaring/ux_decide">Github Repository<a/></strong> for this application for a better look at how <strong>choose</strong> comes to its conclusions.
	</p>
	</p>
</article>
<% end %>

app/views/decisions/show.html.erb
<div class="profile">
<%= content_tag :h3, @decision.name() %>
<%= content_tag :h4, "A #{@decision.type.description} Decision" %>
<p><%= @decision.description %></p>
</div>

<div class="prompt_page">
	<div class="result advice">
		<%= content_tag :h2, "We suggested:" %>
		<%= content_tag :h4, @decision.display_app_choice() %>
	</div>
	<% if current_users_decision %>
		<div class="result response">
			<%= content_tag :h2, "You have chosen:" %>
			<%= content_tag :h4, @decision.display_user_choice() %>
		</div>
		<div class="other_button">
		<%= link_to "Edit Choice", edit_decision_path(@decision) %>
		</div>
		<% if @decision.description != "" %>
			<%= form_for @decision, url: decision_path(@decision), method: :put do |d| %>
				<% if @decision.voting_open %>
					<%= d.submit("Turn Off Voting") %>
				<% else %>
					<%= d.submit("Turn On Voting") %>
				<% end %>
			<% end %>
		<% end %>
	<% else %>
		<% if @decision.voting_open %>
			<h3>Help them out by voting!</h3>
			<%= form_for @vote, url: votes_path(@decision), method: :post do |v| %>
				<%= v.submit("#{@decision.firstoption.description}") %>
				<br><br><br>
				<%= v.submit("#{@decision.secondoption.description}") %>
			<% end %>
		<% else %>	
			<h3>This decision is not open for voting</h3>
		<% end %>
	<% end %>
	<% if @decision.description != "" %>
		<div class="profile">
			<div class="preference_title">
				<%= content_tag :h2, "Total Votes: " + @decision.total_votes().to_s %>
				<%= content_tag :h3, @decision.firstoption.description, :class => "left_option" %>
				<h3 class="or">or</h3>
				<%= content_tag :h3, @decision.secondoption.description, :class => "right_option" %>
			</div>
			<div class="preference_container">
			<%= content_tag :div, "#{@decision.voting_percent(0)}%", :class => "pref_bar_#{@decision.voting_percent(0)} left_bar" %>
			<%= content_tag :div, "#{@decision.voting_percent(1)}%", :class => "pref_bar_#{@decision.voting_percent(1)} right_bar" %>
			</div>
			<br>
		</div>
	<% end %>
</div>
<% if user_signed_in? && current_users_decision %>
	<div class="other_button">
	<%= link_to "Delete Decision", decision_path(@decision), method: :delete, data: {confirm: "Are you sure you want to delete this decision?"} %>
	</div>
<% end %>

app/views/decisions/update.html.erb
<h1>Decisions#update</h1>
<p>Find me in app/views/decisions/update.html.erb</p>